logging.config=classpath:logback-base.xml

pn.env.runtime=PROD
spring.application.name=PN-IO-CONNECTOR
spring.jackson.serialization.write-dates-as-timestamps=false

management.endpoints.web.exposure.include=health,metrics,loggers
spring.threads.virtual.enabled=true

pn.io-connector.io-base-url=${PN_IO_CONNECTOR_IO_BASE_URL:https://api.io.pagopa.it/api/v1}

pn.io-connector.data-vault-base-url=${PN_IO_CONNECTOR_DATA_VAULT_BASE_URL}
pn.io-connector.io-configuration-id=${PN_IO_CONNECTOR_IO_CONFIGURATION_ID}
pn.io-connector.sqs-send-queue-name=${PN_IO_CONNECTOR_SQS_SEND_QUEUE_NAME}
pn.io-connector.sqs-polling-queue-name=${PN_IO_CONNECTOR_SQS_POLLING_QUEUE_NAME}
pn.io-connector.polling-interval-mins=${PN_IO_CONNECTOR_POLLING_INTERVAL_MINS:2880}
pn.io-connector.polling-fixed-interval-seconds=${PN_IO_CONNECTOR_POLLING_FIXED_INTERVAL_SECONDS:0}
pn.io-connector.send-retry-policy=5,10,20,40

pn.commons.retry.max-attempts=${PN_COMMONS_RETRY_MAX_ATTEMPTS:3}
pn.commons.connection-timeout-millis=${PN_COMMONS_CONNECTION_TIMEOUT_MILLIS:10000}
pn.commons.read-timeout-millis=${PN_COMMONS_READ_TIMEOUT_MILLIS:30000}