package it.pagopa.pn.ioconnector.exceptions;

import it.pagopa.pn.commons.exceptions.PnExceptionsCodes;

public final class PnIoConnectorExceptionCodes extends PnExceptionsCodes {

    public static final String ERROR_CODE_IOCONNECTOR_GET_USER_PROFILE_ERROR = "PN_IOCONNECTOR_GET_USER_PROFILE_ERROR";
    public static final String ERROR_CODE_IOCONNECTOR_DATAVAULT_DEANONYMIZE_ERROR = "PN_IOCONNECTOR_DATAVAULT_DEANONYMIZE_ERROR";
    public static final String ERROR_CODE_IOCONNECTOR_SECRETSMANAGER_ERROR = "PN_IOCONNECTOR_SECRETSMANAGER_ERROR";

    public static final String ERROR_CODE_IOCONNECTOR_IO_RECIPIENT_NOT_FOUND = "PN_IO_CONNECTOR_IO_RECIPIENT_NOT_FOUND";
    public static final String ERROR_CODE_IOCONNECTOR_IO_RATE_LIMIT = "PN_IO_CONNECTOR_IO_RATE_LIMIT";
    public static final String ERROR_CODE_IOCONNECTOR_IO_SERVER_ERROR = "PN_IO_CONNECTOR_IO_SERVER_ERROR";
    public static final String ERROR_CODE_IOCONNECTOR_MESSAGE_SERIALIZATION_ERROR = "PN_IOCONNECTOR_MESSAGE_SERIALIZATION_ERROR";
    public static final String ERROR_CODE_IOCONNECTOR_REQUEST_CONFLICT = "PN_IOCONNECTOR_REQUEST_CONFLICT";
    public static final String ERROR_CODE_IOCONNECTOR_INVALID_ATTACHMENT_FORMAT = "PN_IOCONNECTOR_INVALID_ATTACHMENT_FORMAT";

}
