# Logback locale
logging.config=config/logback-local.xml

# Server
server.port=8099

# CORS
cors.allowed.domains=http://localhost:8090,http://localhost:8091

# Runtime mode
pn.env.runtime=DEVELOPMENT
#pn.env.runtime=PROD

pn.io-connector.io-base-url=https://api.io.pagopa.it/api/v1
pn.io-connector.data-vault-base-url=http://localhost:8080

# AWS specific configurations
aws.region-code=us-east-1
aws.profile-name=${PN_AWS_PROFILE_NAME:default}
aws.endpoint-url=http://localhost:4566

# AWS middleware
#pn.middleware.init.aws=true

# DynamoDB
pn.io-connector.dynamodb-table-name=pn-IOConnectorRequests
pn.io-connector.sqs-send-queue-name=pn-io-connector-send-queue

# SecretsManager
pn.io-connector.secrets-name=Pn-IO-Connector-Secrets
